name: CI

on:
  push:
    branches:
      - main
      - '[0-9]+.[0-9]+.x'
      - 'angular-dev-release'
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  adev-deploy:
    if: github.event_name == 'push' && github.ref_name == 'angular-dev-release'
    runs-on: ubuntu-latest
    steps:
      - name: Initialize environment
        uses: angular/dev-infra/github-actions/npm/checkout-and-setup-node@f122b83d2a49e24eb9dfcd54fca9fc97612b832d
      - name: Setup Bazel
        uses: angular/dev-infra/github-actions/bazel/setup@f122b83d2a49e24eb9dfcd54fca9fc97612b832d
      - name: Setup Bazel RBE
        uses: angular/dev-infra/github-actions/bazel/configure-remote@f122b83d2a49e24eb9dfcd54fca9fc97612b832d
      - name: Install node modules
        run: yarn install --frozen-lockfile
      - name: Build adev to ensure it continues to work
        run: yarn bazel build //adev:build
      - name: Deploy to firebase
        uses: ./.github/actions/deploy-docs-site
        with:
          serviceKey: ${{ secrets.ANGULAR_DEV_SITE_DEPLOY }}
          configPath: 'adev/firebase.json'
          distDir: 'dist/bin/adev/build/browser'
